### ISSUE TITLE
controller_license role is failing with :  "AttributeError: 'NoneType' object has no attribute 'get'" [Infra.aap_configuration 3.8.3]

### ISSUE THREAD

**Issue by dczop99-hue** [redhat-cop/automate_tower_genie_collections#1217]
In collection version infra.aap_configuration 3.8.3 there is a bug in role controller_license:

TASK [infra.aap_configuration.controller_license : Validating arguments against arg spec 'main' - An Ansible Role to deploy a license on Ansible Controller.] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'get'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution: 'NoneType' object has no attribute 'get'", "stdout": ""}

Last properly working version of collection is 3.8.0

**Comment by djdanielsson** [comment]
what version of ansible.controller are you using?

**Comment by dczop99-hue** [comment]
latest - ansible-controller-4.7.1

**Comment by djdanielsson** [comment]
what version of AAP are you using?

**Comment by dczop99-hue** [comment]
I've tested this at AAP 2.6

**Comment by djdanielsson** [comment]
I would try the module itself and see if you get the same error. if you do then I would put in a support ticket, if it does work then we will have to investigate further, but this seems likely a module issue.

**Comment by dczop99-hue** [comment]
Hmm, but I've checked this on infra.aap_configuration 3.8.3 and 3.8.0 - I did not change version of ansible.controller. I've only changed version of collection. 
Something changed beetwen 3.8.0 and 3.8.3

**Comment by dbk-rabel** [comment]
We can see the same behaviour: It works with 3.8.0, but we also get this error with 3.8.3
