### PR TITLE
fix controller_license argument_spec

### LINKED ISSUE #1217: controller_license role is failing with :  "AttributeError: 'NoneType' object has no attribute 'get'" [Infra.aap_configuration 3.8.3]
In collection version infra.aap_configuration 3.8.3 there is a bug in role controller_license:

TASK [infra.aap_configuration.controller_license : Validating arguments against arg spec 'main' - An Ansible Role to deploy a license on Ansible Controller.] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'get'
fatal: [localhost]: FAILED! => {"msg": "Unexpected failure during module execution: 'NoneType' object has no attribute 'get'", "stdout": ""}

Last properly working version of collection is 3.8.0

### PR DESCRIPTION
**Pull request by dbk-rabel**
fix #1217

Seems to have been broken in https://github.com/redhat-cop/infra.aap_configuration/pull/1197/files#diff-12a52c1071b3250dac8f0e7dd7ebdc79767fa78a0ddebfd860a5b71b5ca839a5

This fixes #1217 for me. I tested locally.

### CODE REVIEW

**Review by djdanielsson — APPROVED** [review]
thanks for the PR
